server {
    listen 80;
    server_name localhost; 
    
    # Raiz onde os arquivos do Angular foram copiados
    root /usr/share/nginx/html;
    index index.html;

    # Configuração de Logs (Gravando na pasta 'data/frontend' via volume)
    access_log /var/log/nginx/inovatu_access.log;
    error_log /var/log/nginx/inovatu_error.log;

    # Roteamento SPA: Qualquer rota não encontrada redireciona para o index.html
    # Isso impede erro 404 ao dar F5 em uma página interna do Angular [cite: 112]
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de arquivos estáticos para performance (Imagens, JS, CSS)
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public";
    }
}